package dev.elizacamber.glitzglamor

fun getFlagForCountry(country: String) = countryList[country]

val countryList = hashMapOf(
    "Ascension Island" to R.drawable.ac,
    "Andorra" to R.drawable.ad,
    "United Arab Emirates" to R.drawable.ae,
    "Afghanistan" to R.drawable.af,
    "Antigua and Barbuda" to R.drawable.ag,
    "Anguilla" to R.drawable.ai,
    "Albania" to R.drawable.al,
    "Armenia" to R.drawable.am,
    "Angola" to R.drawable.ao,
    "Antarctica" to R.drawable.aq,
    "Argentina" to R.drawable.ar,
    "American Samoa" to R.drawable.asamoa,
    "Austria" to R.drawable.at,
    "Australia" to R.drawable.au,
    "Aruba" to R.drawable.aw,
    "Aland Islands" to R.drawable.ax,
    "Azerbaijan" to R.drawable.az,
    "Bosnia and Herzegovina" to R.drawable.ba,
    "Barbados" to R.drawable.bb,
    "Bangladesh" to R.drawable.bd,
    "Belgium" to R.drawable.be,
    "Burkina Faso" to R.drawable.bf,
    "Bulgaria" to R.drawable.bg,
    "Bahrain" to R.drawable.bh,
    "Burundi" to R.drawable.bi,
    "Benin" to R.drawable.bj,
    "Saint Barth\u00e9lemy" to R.drawable.bl,
    "Bermuda" to R.drawable.bm,
    "Brunei Darussalam" to R.drawable.bn,
    "Bolivia (Plurinational State of)" to R.drawable.bo,
    "Bonaire, Sint Eustatius and Saba" to R.drawable.bq,
    "Brazil" to R.drawable.br,
    "Bahamas" to R.drawable.bs,
    "Bhutan" to R.drawable.bt,
    "Bouvet Island" to R.drawable.bv,
    "Botswana" to R.drawable.bw,
    "Belarus" to R.drawable.by,
    "Belize" to R.drawable.bz,
    "Canada" to R.drawable.ca,
    "Cocos (Keeling) Islands" to R.drawable.cc,
    "Democratic Republic of the Congo" to R.drawable.cd,
    "Central European Free Trade Agreement" to R.drawable.cefta,
    "Central African Republic" to R.drawable.cf,
    "Republic of the Congo" to R.drawable.cg,
    "Switzerland" to R.drawable.ch,
    "Cote d'Ivoire" to R.drawable.ci,
    "Cook Islands" to R.drawable.ck,
    "Chile" to R.drawable.cl,
    "Cameroon" to R.drawable.cm,
    "China" to R.drawable.cn,
    "Colombia" to R.drawable.co,
    "Clipperton Island" to R.drawable.cp,
    "Costa Rica" to R.drawable.cr,
    "Cuba" to R.drawable.cu,
    "Cabo Verde" to R.drawable.cv,
    "Cura\u00e7ao" to R.drawable.cw,
    "Christmas Island" to R.drawable.cx,
    "Cyprus" to R.drawable.cy,
    "Czech Republic" to R.drawable.cz,
    "Germany" to R.drawable.de,
    "Diego Garcia" to R.drawable.dg,
    "Djibouti" to R.drawable.dj,
    "Denmark" to R.drawable.dk,
    "Dominica" to R.drawable.dm,
    "Dominican Republic" to R.drawable.do_rep,
    "Algeria" to R.drawable.dz,
    "Ceuta & Melilla" to R.drawable.ea,
    "Ecuador" to R.drawable.ec,
    "Estonia" to R.drawable.ee,
    "Egypt" to R.drawable.eg,
    "Western Sahara" to R.drawable.eh,
    "Eritrea" to R.drawable.er,
    "Spain" to R.drawable.es,
    "Catalonia" to R.drawable.es_ct,
    "Galicia" to R.drawable.es_ga,
    "Ethiopia" to R.drawable.et,
    "Finland" to R.drawable.fi,
    "Fiji" to R.drawable.fj,
    "Falkland Islands" to R.drawable.fk,
    "Federated States of Micronesia" to R.drawable.fm,
    "Faroe Islands" to R.drawable.fo,
    "France" to R.drawable.fr,
    "Gabon" to R.drawable.ga,
    "United Kingdom" to R.drawable.gb,
    "England" to R.drawable.gb_eng,
    "Northern Ireland" to R.drawable.gb_nir,
    "Scotland" to R.drawable.gb_sct,
    "Wales" to R.drawable.gb_wls,
    "Grenada" to R.drawable.gd,
    "Georgia" to R.drawable.ge,
    "French Guiana" to R.drawable.gf,
    "Guernsey" to R.drawable.gg,
    "Ghana" to R.drawable.gh,
    "Gibraltar" to R.drawable.gi,
    "Greenland" to R.drawable.gl,
    "Gambia" to R.drawable.gm,
    "Guinea" to R.drawable.gn,
    "Guadeloupe" to R.drawable.gp,
    "Equatorial Guinea" to R.drawable.gq,
    "Greece" to R.drawable.gr,
    "South Georgia and the South Sandwich Islands" to R.drawable.gs,
    "Guatemala" to R.drawable.gt,
    "Guam" to R.drawable.gu,
    "Guinea-Bissau" to R.drawable.gw,
    "Guyana" to R.drawable.gy,
    "Hong Kong" to R.drawable.hk,
    "Heard Island and McDonald Islands" to R.drawable.hm,
    "Honduras" to R.drawable.hn,
    "Croatia" to R.drawable.hr,
    "Haiti" to R.drawable.ht,
    "Hungary" to R.drawable.hu,
    "Canary Islands" to R.drawable.ic,
    "Indonesia" to R.drawable.id,
    "Ireland" to R.drawable.ie,
    "Israel" to R.drawable.il,
    "Isle of Man" to R.drawable.im,
    "India" to R.drawable.ind,
    "British Indian Ocean Territory" to R.drawable.io,
    "Iraq" to R.drawable.iq,
    "Iran (Islamic Republic of)" to R.drawable.ir,
    "Iceland" to R.drawable.ice,
    "Italy" to R.drawable.it,
    "Jersey" to R.drawable.je,
    "Jamaica" to R.drawable.jm,
    "Jordan" to R.drawable.jo,
    "Japan" to R.drawable.jp,
    "Kenya" to R.drawable.ke,
    "Kyrgyzstan" to R.drawable.kg,
    "Cambodia" to R.drawable.kh,
    "Kiribati" to R.drawable.ki,
    "Comoros" to R.drawable.km,
    "Saint Kitts and Nevis" to R.drawable.kn,
    "North Korea" to R.drawable.kp,
    "South Korea" to R.drawable.kr,
    "Kuwait" to R.drawable.kw,
    "Cayman Islands" to R.drawable.ky,
    "Kazakhstan" to R.drawable.kz,
    "Laos" to R.drawable.la,
    "Lebanon" to R.drawable.lb,
    "Saint Lucia" to R.drawable.lc,
    "Liechtenstein" to R.drawable.li,
    "Sri Lanka" to R.drawable.lk,
    "Liberia" to R.drawable.lr,
    "Lesotho" to R.drawable.ls,
    "Lithuania" to R.drawable.lt,
    "Luxembourg" to R.drawable.lu,
    "Latvia" to R.drawable.lv,
    "Libya" to R.drawable.ly,
    "Morocco" to R.drawable.ma,
    "Monaco" to R.drawable.mc,
    "Moldova" to R.drawable.md,
    "Montenegro" to R.drawable.me,
    "Saint Martin" to R.drawable.mf,
    "Madagascar" to R.drawable.mg,
    "Marshall Islands" to R.drawable.mh,
    "North Macedonia" to R.drawable.mk,
    "Mali" to R.drawable.ml,
    "Myanmar" to R.drawable.mm,
    "Mongolia" to R.drawable.mn,
    "Macau" to R.drawable.mo,
    "Northern Mariana Islands" to R.drawable.mp,
    "Martinique" to R.drawable.mq,
    "Mauritania" to R.drawable.mr,
    "Montserrat" to R.drawable.ms,
    "Malta" to R.drawable.mt,
    "Mauritius" to R.drawable.mu,
    "Maldives" to R.drawable.mv,
    "Malawi" to R.drawable.mw,
    "Mexico" to R.drawable.mx,
    "Malaysia" to R.drawable.my,
    "Mozambique" to R.drawable.mz,
    "Namibia" to R.drawable.na,
    "New Caledonia" to R.drawable.nc,
    "Niger" to R.drawable.ne,
    "Norfolk Island" to R.drawable.nf,
    "Nigeria" to R.drawable.ng,
    "Nicaragua" to R.drawable.ni,
    "Netherlands" to R.drawable.nl,
    "Norway" to R.drawable.no,
    "Nepal" to R.drawable.np,
    "Nauru" to R.drawable.nr,
    "Niue" to R.drawable.nu,
    "New Zealand" to R.drawable.nz,
    "Oman" to R.drawable.om,
    "Panama" to R.drawable.pa,
    "Peru" to R.drawable.pe,
    "French Polynesia" to R.drawable.pf,
    "Papua New Guinea" to R.drawable.pg,
    "Philippines" to R.drawable.ph,
    "Pakistan" to R.drawable.pk,
    "Poland" to R.drawable.pl,
    "Saint Pierre and Miquelon" to R.drawable.pm,
    "Pitcairn" to R.drawable.pn,
    "Puerto Rico" to R.drawable.pr,
    "State of Palestine" to R.drawable.ps,
    "Portugal" to R.drawable.pt,
    "Palau" to R.drawable.pw,
    "Paraguay" to R.drawable.py,
    "Qatar" to R.drawable.qa,
    "R\u00e9union" to R.drawable.re,
    "Romania" to R.drawable.ro,
    "Serbia" to R.drawable.rs,
    "Russia" to R.drawable.ru,
    "Rwanda" to R.drawable.rw,
    "Saudi Arabia" to R.drawable.sa,
    "Solomon Islands" to R.drawable.sb,
    "Seychelles" to R.drawable.sc,
    "Sudan" to R.drawable.sd,
    "Sweden" to R.drawable.se,
    "Singapore" to R.drawable.sg,
    "Saint Helena, Ascension and Tristan da Cunha" to R.drawable.sh,
    "Slovenia" to R.drawable.si,
    "Svalbard and Jan Mayen" to R.drawable.sj,
    "Slovakia" to R.drawable.sk,
    "Sierra Leone" to R.drawable.sl,
    "San Marino" to R.drawable.sm,
    "Senegal" to R.drawable.sn,
    "Somalia" to R.drawable.so,
    "Suriname" to R.drawable.sr,
    "South Sudan" to R.drawable.ss,
    "Sao Tome and Principe" to R.drawable.st,
    "El Salvador" to R.drawable.sv,
    "Sint Maarten" to R.drawable.sx,
    "Syria" to R.drawable.sy,
    "Eswatini" to R.drawable.sz,
    "Tristan da Cunha" to R.drawable.ta,
    "Turks and Caicos Islands" to R.drawable.tc,
    "Chad" to R.drawable.td,
    "French Southern Territories" to R.drawable.tf,
    "Togo" to R.drawable.tg,
    "Thailand" to R.drawable.th,
    "Tajikistan" to R.drawable.tj,
    "Tokelau" to R.drawable.tk,
    "Timor-Leste" to R.drawable.tl,
    "Turkmenistan" to R.drawable.tm,
    "Tunisia" to R.drawable.tn,
    "Tonga" to R.drawable.to,
    "Turkey" to R.drawable.tr,
    "Trinidad and Tobago" to R.drawable.tt,
    "Tuvalu" to R.drawable.tv,
    "Taiwan" to R.drawable.tw,
    "Tanzania" to R.drawable.tz,
    "Ukraine" to R.drawable.ua,
    "Uganda" to R.drawable.ug,
    "United States Minor Outlying Islands" to R.drawable.um,
    "United States of America" to R.drawable.us,
    "Uruguay" to R.drawable.uy,
    "Uzbekistan" to R.drawable.uz,
    "Holy See" to R.drawable.va,
    "Saint Vincent and the Grenadines" to R.drawable.vc,
    "Venezuela (Bolivarian Republic of)" to R.drawable.ve,
    "Virgin Islands (British)" to R.drawable.vg,
    "Virgin Islands (U.S.)" to R.drawable.vi,
    "Vietnam" to R.drawable.vn,
    "Vanuatu" to R.drawable.vu,
    "Wallis and Futuna" to R.drawable.wf,
    "Samoa" to R.drawable.ws,
    "Kosovo" to R.drawable.xk,
    "Unknown" to R.drawable.xx,
    "Yemen" to R.drawable.ye,
    "Mayotte" to R.drawable.yt,
    "South Africa" to R.drawable.za,
    "Zambia" to R.drawable.zm,
    "Zimbabwe" to R.drawable.zw,
)